steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/java-starter-image', '.' ]
images:
- 'gcr.io/$PROJECT_ID/java-starter-image'
artifacts:
  objects:
    location: "gs://${_BUCKET}/"
    paths:
    - "target/${_TARGET}"
